# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)
b <- board_folder(path = "/tmp/RtmpyOdYSh/pins-532d4b708dd3")
v <- vetiver_pin_read(b, "credit-risk", version = "20221127T004525Z-f54ee")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v)
}
