# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)
b <- board_folder(path = "/tmp/Rtmp3e9m6p/pins-434f433f178")
v <- vetiver_pin_read(b, "credit-risk", version = "20221126T234915Z-1c5d4")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v)
}
