# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)
b <- board_folder(path = "/tmp/Rtmpm27D5I/pins-1232cde5377")
v <- vetiver_pin_read(b, "credit-risk", version = "20221126T214524Z-ac84d")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v)
}
